.PHONY: clean All

All:
	@echo "----------Building project:[ cppBeginToBeyond - Debug ]----------"
	@cd "cppBeginToBeyond" && "$(MAKE)" -f  "cppBeginToBeyond.mk"
clean:
	@echo "----------Cleaning project:[ cppBeginToBeyond - Debug ]----------"
	@cd "cppBeginToBeyond" && "$(MAKE)" -f  "cppBeginToBeyond.mk" clean
